<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>placeholder_username</name>
   <tag></tag>
   <elementGuidId>f894b6a4-8a3e-4bcf-bb61-9bd26c70f6ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='user-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='user-name']</value>
      <webElementGuid>b1a82094-7797-4bd3-9e05-09909fc7976f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
