<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_message_error_login</name>
   <tag></tag>
   <elementGuidId>9f3b9069-98a2-4daa-9b00-3545806f6660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h3[@data-test='error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h3[@data-test='error']</value>
      <webElementGuid>3841e8de-745e-410d-be3e-37cf8df9b0e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
