<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_logo</name>
   <tag></tag>
   <elementGuidId>2cbdefbc-240c-485f-9c16-a83a0c71fe7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='app_logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='app_logo']</value>
      <webElementGuid>63ec49f3-391a-442b-86de-6d26f4ac45b1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
